baseURL = 'https://KuleenS.github.io/blog-hugo'
languageCode = 'en-us'
title = 'blog'
theme = 'stack'

[params]
  author = "Kuleen Sasse"
  description = "A blog about on random thoughts on NLP, GIS, Optimization and more"

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/KuleenS"

  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/KuleenSasse"